import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { useDisclosure } from "@mantine/hooks"
import { Modal, Button, Group, Select } from "@mantine/core"

export default function Home() {
  const [opened, { open, close }] = useDisclosure(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Modal opened={opened} onClose={close} title="Authentication">
          {/* Modal content */}
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => (
            <Select
              key={i}
              label="Your favorite framework/library"
              size="xl"
              data={[
                { value: "react", label: "React" },
                { value: "ng", label: "Angular" },
                { value: "svelte", label: "Svelte" },
                { value: "vue", label: "Vue" },
              ]}
            />
          ))}
        </Modal>

        <Group position="center">
          <Button onClick={open}>Open modal</Button>
        </Group>
      </main>
    </>
  )
}
